runtime: python37 # or python37 for Python 3.7
entrypoint: gunicorn -b :$PORT -w 2 server:app --timeout 300

instance_class: F2

env_variables:
  PROJECT_ID: "gense" # put the GCP project id (ex : gense-1ab2c)
  SERVER_REGION: "us-central1" #put the region of server (ex : us-central1)
  COMPUTE_IMAGE_QUEUE: "compute-image-task" #the name of the task queue

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto